version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: anki_web
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped
    networks:
      - web_network

networks:
  web_network:
    driver: bridge
    name: anki_web_network 